### PR TITLE
More parsing

### PR DESCRIPTION
**Pull request by julian-shalaby**

### CODE REVIEW

**Comment by julian-shalaby** [comment]
In this PR:
* Changed name to db_sigma. I couldn't get it working properly named as sigma due to the naming conflict
* Created a class called SigmaRule. This takes a Sigma rule, parses the SQL filter with DatabricksBackend, and grabs all available variables from it's from_yaml conversion and dynamically creates class variables from them
* Extended the field_quote_pattern to support struct and map columns. Previously it would wrap columns containing periods with `` and throw an error

**Comment by julian-shalaby** [comment]
This will be used for the tickets https://databricks.atlassian.net/browse/DET-1081 and https://databricks.atlassian.net/browse/GTMSEC-246

**Review by alexott — CHANGES_REQUESTED** [review]
This package is designed to be used with [sigma-cli](https://github.com/SigmaHQ/sigma-cli) that provides an interface to rules loading, necessary transformation via pipelines (for example to convert field names to a specific implementation), etc. Because of this it follows the specific directories structure, and these renames, etc. will break it. 

Please revert back to original directory structure

**Review by alexott — COMMENTED** [review]
We need to remove `sigma/__init__.py` and `sigma/backends/__init__.py` as they may conflict with files provided by other sigma packages.

I also think that LinkParser & Rule classes could be done in a separate project - backend should be responsible for files conversion, without need to know from where data is coming.

**Comment by alexott** [comment]
I've merged the fix for maps/structs, but I would prefer to leave the rest of changes out of the backend...

**Pull request closed without merging**
